/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/11/2022 7:52:10 PM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;
using System.Text.Json;

namespace GizmoFort.Connector.ERPNext.ERPTypes.LoanManagement.RepaymentSchedule
{
    public partial class ERP_LoanManagement_RepaymentSchedule : 
        ERPNextObjectBase, 
        ISerializePropertiesToJson, 
        IDeserializePropertiesFromJson<ERPNextObjectBase>
    {
        public ERP_LoanManagement_RepaymentSchedule() : this(new ERPObject(_DockType.LoanManagement_RepaymentSchedule)) { }
        public ERP_LoanManagement_RepaymentSchedule(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_LoanManagement_RepaymentSchedule>(propertyName);
        }

        public static string? GetPropertyName(string columnName)
        {
            return ERPNextObjectBase.GetPropertyName<ERP_LoanManagement_RepaymentSchedule>(columnName);
        }

        public string Serialize()
        {
            //
            // serializtion is more complex... will need to serialize the data
            // property ONLY, but map the names to the exposed property names
            //
            var options = new JsonSerializerOptions
            {
                DictionaryKeyPolicy = new CustomJsonSerializationPolicy<ERP_LoanManagement_RepaymentSchedule>()
            };
            return JsonSerializer.Serialize(value: this.data,
                                            options: options);
        }

        public static ERP_LoanManagement_RepaymentSchedule? Deserialize(string json)
        {
            //
            // deserialization is straight-forward... setters will only be called if values
            // are included in the json string
            //
            return JsonSerializer.Deserialize<ERP_LoanManagement_RepaymentSchedule>(json: json);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("payment_date")]
        public DateOnly? PaymentDate
        {
            get { return data.payment_date; }
            set { data.payment_date = value; }
        }

        [Column("principal_amount")]
        public decimal PrincipalAmount
        {
            get { return data.principal_amount; }
            set { data.principal_amount = value; }
        }

        [Column("interest_amount")]
        public decimal InterestAmount
        {
            get { return data.interest_amount; }
            set { data.interest_amount = value; }
        }

        [Column("total_payment")]
        public decimal TotalPayment
        {
            get { return data.total_payment; }
            set { data.total_payment = value; }
        }

        [Column("balance_loan_amount")]
        public decimal BalanceLoanAmount
        {
            get { return data.balance_loan_amount; }
            set { data.balance_loan_amount = value; }
        }

        [Column("is_accrued")]
        public int IsAccrued
        {
            get { return data.is_accrued; }
            set { data.is_accrued = value; }
        }

        [Column("parent")]
        public string? Parent
        {
            get { return data.parent; }
            set { data.parent = value; }
        }

        [Column("parentfield")]
        public string? Parentfield
        {
            get { return data.parentfield; }
            set { data.parentfield = value; }
        }

        [Column("parenttype")]
        public string? Parenttype
        {
            get { return data.parenttype; }
            set { data.parenttype = value; }
        }


    }
}

