/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/12/2022 2:29:08 PM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;
using System.Text.Json;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Telephony.IncomingCallHandlingSchedule
{
    public partial class ERP_Telephony_IncomingCallHandlingSchedule : ERPNextObjectBase
    {
        public ERP_Telephony_IncomingCallHandlingSchedule() : this(new ERPObject(_DockType.Telephony_IncomingCallHandlingSchedule)) { }
        public ERP_Telephony_IncomingCallHandlingSchedule(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Telephony_IncomingCallHandlingSchedule>(propertyName);
        }

        public static string? GetPropertyName(string columnName)
        {
            return ERPNextObjectBase.GetPropertyName<ERP_Telephony_IncomingCallHandlingSchedule>(columnName);
        }


        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTimeOffset? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTimeOffset? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("day_of_week")]
        public string? DayOfWeek
        {
            get { return data.day_of_week; }
            set { data.day_of_week = value; }
        }

        [Column("from_time")]
        public TimeSpan? FromTime
        {
            get { return data.from_time; }
            set { data.from_time = value; }
        }

        [Column("to_time")]
        public TimeSpan? ToTime
        {
            get { return data.to_time; }
            set { data.to_time = value; }
        }

        [Column("agent_group")]
        public string? AgentGroup
        {
            get { return data.agent_group; }
            set { data.agent_group = value; }
        }

        [Column("parent")]
        public string? Parent
        {
            get { return data.parent; }
            set { data.parent = value; }
        }

        [Column("parentfield")]
        public string? Parentfield
        {
            get { return data.parentfield; }
            set { data.parentfield = value; }
        }

        [Column("parenttype")]
        public string? Parenttype
        {
            get { return data.parenttype; }
            set { data.parenttype = value; }
        }


    }
}

