/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/11/2022 7:52:10 PM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;
using System.Text.Json;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Accounts.PaymentTerm
{
    public partial class ERP_Accounts_PaymentTerm : 
        ERPNextObjectBase, 
        ISerializePropertiesToJson, 
        IDeserializePropertiesFromJson<ERPNextObjectBase>
    {
        public ERP_Accounts_PaymentTerm() : this(new ERPObject(_DockType.Accounts_PaymentTerm)) { }
        public ERP_Accounts_PaymentTerm(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Accounts_PaymentTerm>(propertyName);
        }

        public static string? GetPropertyName(string columnName)
        {
            return ERPNextObjectBase.GetPropertyName<ERP_Accounts_PaymentTerm>(columnName);
        }

        public string Serialize()
        {
            //
            // serializtion is more complex... will need to serialize the data
            // property ONLY, but map the names to the exposed property names
            //
            var options = new JsonSerializerOptions
            {
                DictionaryKeyPolicy = new CustomJsonSerializationPolicy<ERP_Accounts_PaymentTerm>()
            };
            return JsonSerializer.Serialize(value: this.data,
                                            options: options);
        }

        public static ERP_Accounts_PaymentTerm? Deserialize(string json)
        {
            //
            // deserialization is straight-forward... setters will only be called if values
            // are included in the json string
            //
            return JsonSerializer.Deserialize<ERP_Accounts_PaymentTerm>(json: json);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("payment_term_name")]
        public string? PaymentTermName
        {
            get { return data.payment_term_name; }
            set { data.payment_term_name = value; }
        }

        [Column("invoice_portion")]
        public decimal InvoicePortion
        {
            get { return data.invoice_portion; }
            set { data.invoice_portion = value; }
        }

        [Column("mode_of_payment")]
        public string? ModeOfPayment
        {
            get { return data.mode_of_payment; }
            set { data.mode_of_payment = value; }
        }

        [Column("due_date_based_on")]
        public string? DueDateBasedOn
        {
            get { return data.due_date_based_on; }
            set { data.due_date_based_on = value; }
        }

        [Column("credit_days")]
        public int CreditDays
        {
            get { return data.credit_days; }
            set { data.credit_days = value; }
        }

        [Column("credit_months")]
        public int CreditMonths
        {
            get { return data.credit_months; }
            set { data.credit_months = value; }
        }

        [Column("discount_type")]
        public string? DiscountType
        {
            get { return data.discount_type; }
            set { data.discount_type = value; }
        }

        [Column("discount")]
        public decimal Discount
        {
            get { return data.discount; }
            set { data.discount = value; }
        }

        [Column("discount_validity_based_on")]
        public string? DiscountValidityBasedOn
        {
            get { return data.discount_validity_based_on; }
            set { data.discount_validity_based_on = value; }
        }

        [Column("discount_validity")]
        public int DiscountValidity
        {
            get { return data.discount_validity; }
            set { data.discount_validity = value; }
        }

        [Column("description")]
        public string? Description
        {
            get { return data.description; }
            set { data.description = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

